# coding: utf-8

"""
    Metal API

    desc  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest
import datetime

import equinix_metal
from equinix_metal.models.ip_assignment import IPAssignment  # noqa: E501
from equinix_metal.rest import ApiException

class TestIPAssignment(unittest.TestCase):
    """IPAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IPAssignment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IPAssignment`
        """
        model = equinix_metal.models.ip_assignment.IPAssignment()  # noqa: E501
        if include_optional :
            return IPAssignment(
                address = '', 
                address_family = 56, 
                assigned_to = equinix_metal.models.href.Href(
                    href = '', ), 
                cidr = 56, 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                enabled = True, 
                gateway = '', 
                global_ip = True, 
                href = '', 
                id = '', 
                manageable = True, 
                management = True, 
                metro = None, 
                netmask = '', 
                network = '', 
                parent_block = equinix_metal.models.parent_block.ParentBlock(
                    cidr = 56, 
                    href = '', 
                    netmask = '', 
                    network = '', ), 
                public = True
            )
        else :
            return IPAssignment(
                assigned_to = equinix_metal.models.href.Href(
                    href = '', ),
        )
        """

    def testIPAssignment(self):
        """Test IPAssignment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
