# coding: utf-8

"""
    Metal API

    desc  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from equinix_metal.models.metro import Metro
from equinix_metal.models.project import Project
from equinix_metal.models.user import User

class Vrf(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = Field(None, description="Optional field that can be set to describe the VRF")
    local_asn: Optional[StrictInt] = Field(None, description="A 4-byte ASN associated with the VRF.")
    ip_ranges: Optional[List[StrictStr]] = Field(None, description="A list of CIDR network addresses. Like [\"10.0.0.0/16\", \"2001:d78::/56\"].")
    project: Optional[Project] = None
    metro: Optional[Metro] = None
    created_by: Optional[User] = None
    href: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    __properties = ["id", "name", "description", "local_asn", "ip_ranges", "project", "metro", "created_by", "href", "created_at", "updated_at"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Vrf:
        """Create an instance of Vrf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of project
        if self.project:
            _dict['project'] = self.project.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metro
        if self.metro:
            _dict['metro'] = self.metro.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['created_by'] = self.created_by.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Vrf:
        """Create an instance of Vrf from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return Vrf.parse_obj(obj)

        _obj = Vrf.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "local_asn": obj.get("local_asn"),
            "ip_ranges": obj.get("ip_ranges"),
            "project": Project.from_dict(obj.get("project")) if obj.get("project") is not None else None,
            "metro": Metro.from_dict(obj.get("metro")) if obj.get("metro") is not None else None,
            "created_by": User.from_dict(obj.get("created_by")) if obj.get("created_by") is not None else None,
            "href": obj.get("href"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj

