name: Do GitHub release  and publish to PyPI
on:
  workflow_dispatch:

env:
  PACKAGE_DIR: equinix_metal
  DIST_DIR: equinix_metal/dist
  PYTHON_VERSION: 3.8
jobs:
  build:
    name: Build and publish package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      working-directory: ${{ env.PACKAGE_DIR }}
      run: |
        python -m pip install --upgrade build

    - name: Build package
      working-directory: ${{ env.PACKAGE_DIR }}
      run: |
        python -m build --sdist --wheel --outdir dist/ .

    - name: Upload to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: ${{ env.DIST_DIR }}

    - name: Do GitHub release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.0
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: equinix-labs@auto-commit-workflow
          GIT_AUTHOR_EMAIL: bot@equinix.noreply.github.com
          GIT_COMMITTER_NAME: equinix-labs@auto-commit-workflow
          GIT_COMMITTER_EMAIL: bot@equinix.noreply.github.com


